import { createContainer } from "../src/core/container.js";
import { createKv } from "../src/adapters/kv/index.js";
import { createIds } from "../src/core/ports/ids.js";
import { createClock } from "../src/core/ports/clock.js";
import { createPlaceRepository } from "../src/contexts/discovery/repository.js";

const run = async () => {
  console.log("🌱 Seeding Catalonia Data (500 Places)...");

  // 1. Setup DI
  const container = createContainer();
  const kv = await createKv();

  container.register('kv', () => kv, 'singleton');
  container.register('ids', createIds, 'singleton');
  container.register('clock', createClock, 'singleton');
  container.register('discovery.repository', createPlaceRepository, 'singleton');

  const repo = container.resolve('discovery.repository');

  // 2. Clear DB
  console.log("🧹 Clearing database...");
  await repo.removeAll();

  // 3. Define Real Data (~500 Places)
  const places = [

    // --- CULTURE (40) ---
    { "name": "Sagrada Família", "lat": 41.4036, "lon": 2.1744, "cat": "culture", "tags": ["gaudi", "church", "unesco"] },
    { "name": "Casa Batlló", "lat": 41.3917, "lon": 2.1649, "cat": "culture", "tags": ["gaudi", "modernisme"] },
    { "name": "Casa Milà (La Pedrera)", "lat": 41.3954, "lon": 2.1620, "cat": "culture", "tags": ["gaudi", "modernisme"] },
    { "name": "Picasso Museum", "lat": 41.3853, "lon": 2.1809, "cat": "culture", "tags": ["art", "museum"] },
    { "name": "Camp Nou", "lat": 41.3809, "lon": 2.1228, "cat": "culture", "tags": ["football", "barca"] },
    { "name": "Gothic Quarter", "lat": 41.3825, "lon": 2.1769, "cat": "culture", "tags": ["history", "old_town"] },
    { "name": "Palau de la Música Catalana", "lat": 41.3875, "lon": 2.1753, "cat": "culture", "tags": ["music", "architecture"] },
    { "name": "Cathedral of Barcelona", "lat": 41.3840, "lon": 2.1762, "cat": "culture", "tags": ["gothic", "church"] },
    { "name": "MNAC (National Art Museum)", "lat": 41.3686, "lon": 2.1534, "cat": "culture", "tags": ["art", "museum", "view"] },
    { "name": "Fundació Joan Miró", "lat": 41.3686, "lon": 2.1598, "cat": "culture", "tags": ["art", "museum"] },
    { "name": "Recinte Modernista de Sant Pau", "lat": 41.4124, "lon": 2.1744, "cat": "culture", "tags": ["hospital", "architecture"] },
    { "name": "Santa Maria del Mar", "lat": 41.3835, "lon": 2.1821, "cat": "culture", "tags": ["gothic", "church"] },
    { "name": "Poble Espanyol", "lat": 41.3695, "lon": 2.1469, "cat": "culture", "tags": ["architecture", "village"] },
    { "name": "Arc de Triomf", "lat": 41.3911, "lon": 2.1806, "cat": "culture", "tags": ["monument", "history"] },
    { "name": "Catedral de Girona", "lat": 41.9875, "lon": 2.8262, "cat": "culture", "tags": ["gothic", "history"] },
    { "name": "Jewish Quarter (Girona)", "lat": 41.9866, "lon": 2.8261, "cat": "culture", "tags": ["history", "medieval"] },
    { "name": "Dali Museum", "lat": 42.2680, "lon": 2.9596, "cat": "culture", "tags": ["art", "surrealism", "figueres"] },
    { "name": "Tossa de Mar Castle", "lat": 41.7166, "lon": 2.9340, "cat": "culture", "tags": ["castle", "beach"] },
    { "name": "Begur Castle", "lat": 41.9546, "lon": 3.2074, "cat": "culture", "tags": ["view", "medieval"] },
    { "name": "Empúries Ruins", "lat": 42.1337, "lon": 3.1206, "cat": "culture", "tags": ["greek", "roman"] },
    { "name": "Amphitheatre of Tarragona", "lat": 41.1148, "lon": 1.2593, "cat": "culture", "tags": ["roman", "history"] },
    { "name": "Pont del Diable", "lat": 41.1444, "lon": 1.2415, "cat": "culture", "tags": ["aqueduct", "roman"] },
    { "name": "Sitges Church", "lat": 41.2343, "lon": 1.8115, "cat": "culture", "tags": ["beach", "iconic"] },
    { "name": "Montserrat Monastery", "lat": 41.5931, "lon": 1.8375, "cat": "culture", "tags": ["mountain", "monastery"] },
    { "name": "Taüll Churches", "lat": 42.5190, "lon": 0.8499, "cat": "culture", "tags": ["romanesque", "unesco"] },
    { "name": "Monestir de Poblet", "lat": 41.3810, "lon": 1.0790, "cat": "culture", "tags": ["cistercian", "unesco"] },
    { "name": "Monestir de Santes Creus", "lat": 41.3556, "lon": 1.3622, "cat": "culture", "tags": ["cistercian", "gothic"] },
    { "name": "Castell de Cardona", "lat": 41.9142, "lon": 1.6853, "cat": "culture", "tags": ["castle", "hotel"] },
    { "name": "Besalú Bridge", "lat": 42.1996, "lon": 2.7001, "cat": "culture", "tags": ["medieval", "bridge"] },
    { "name": "Tarragona Roman Circus", "lat": 41.1165, "lon": 1.2562, "cat": "culture", "tags": ["roman", "ruins"] },
    { "name": "Colonia Güell", "lat": 41.3623, "lon": 2.0287, "cat": "culture", "tags": ["gaudi", "crypt"] },
    { "name": "Palau Güell", "lat": 41.3790, "lon": 2.1742, "cat": "culture", "tags": ["gaudi", "palace"] },
    { "name": "Casa Vicens", "lat": 41.4035, "lon": 2.1507, "cat": "culture", "tags": ["gaudi", "museum"] },
    { "name": "Vic Cathedral", "lat": 41.9288, "lon": 2.2563, "cat": "culture", "tags": ["neoclassical", "church"] },
    { "name": "Castell de Miravet", "lat": 41.0425, "lon": 0.5968, "cat": "culture", "tags": ["castle", "river"] },
    { "name": "La Seu Vella (Lleida)", "lat": 41.6181, "lon": 0.6270, "cat": "culture", "tags": ["cathedral", "view"] },
    { "name": "Castell de Montjuïc", "lat": 41.3635, "lon": 2.1661, "cat": "culture", "tags": ["castle", "military"] },
    { "name": "Cementiri de Montjuïc", "lat": 41.3550, "lon": 2.1550, "cat": "culture", "tags": ["cemetery", "art"] },
    { "name": "Hospital de Sant Pau", "lat": 41.4116, "lon": 2.1748, "cat": "culture", "tags": ["modernisme", "unesco"] },
    { "name": "Museu Marítim de Barcelona", "lat": 41.3761, "lon": 2.1756, "cat": "culture", "tags": ["maritime", "history"] },
    { "name": "Pavelló Mies van der Rohe", "lat": 41.3706, "lon": 2.1502, "cat": "culture", "tags": ["modernism", "architecture"] },

    // --- GASTRONOMY (40) ---
    { "name": "Mercat de la Boqueria", "lat": 41.3817, "lon": 2.1716, "cat": "gastronomy", "tags": ["market", "food"] },
    { "name": "El Xampanyet", "lat": 41.3845, "lon": 2.1811, "cat": "gastronomy", "tags": ["tapas", "historic"] },
    { "name": "Disfrutar", "lat": 41.3878, "lon": 2.1533, "cat": "gastronomy", "tags": ["michelin", "innovative"] },
    { "name": "Tickets (Teatre)", "lat": 41.3768, "lon": 2.1565, "cat": "gastronomy", "tags": ["tapas", "elbulli"] },
    { "name": "Can Culleretes", "lat": 41.3807, "lon": 2.1743, "cat": "gastronomy", "tags": ["historic", "catalan"] },
    { "name": "Els Quatre Gats", "lat": 41.3858, "lon": 2.1738, "cat": "gastronomy", "tags": ["picasso", "historic"] },
    { "name": "7 Portes", "lat": 41.3823, "lon": 2.1837, "cat": "gastronomy", "tags": ["paella", "historic"] },
    { "name": "Quimet & Quimet", "lat": 41.3734, "lon": 2.1643, "cat": "gastronomy", "tags": ["tapas", "bodega"] },
    { "name": "El Celler de Can Roca", "lat": 41.9937, "lon": 2.8083, "cat": "gastronomy", "tags": ["michelin", "world_best"] },
    { "name": "Can Paixano (La Xampanyeria)", "lat": 41.3817, "lon": 2.1843, "cat": "gastronomy", "tags": ["cava", "tapas"] },
    { "name": "Cervecería Catalana", "lat": 41.3924, "lon": 2.1627, "cat": "gastronomy", "tags": ["tapas", "popular"] },
    { "name": "El Nacional", "lat": 41.3895, "lon": 2.1678, "cat": "gastronomy", "tags": ["food_hall", "beautiful"] },
    { "name": "Can Majó", "lat": 41.3775, "lon": 2.1892, "cat": "gastronomy", "tags": ["seafood", "beach"] },
    { "name": "Bar Cañete", "lat": 41.3795, "lon": 2.1725, "cat": "gastronomy", "tags": ["tapas", "lively"] },
    { "name": "Dos Palillos", "lat": 41.3828, "lon": 2.1689, "cat": "gastronomy", "tags": ["asian", "tapas"] },
    { "name": "Alkimia", "lat": 41.3965, "lon": 2.1625, "cat": "gastronomy", "tags": ["michelin", "design"] },
    { "name": "Lasarte", "lat": 41.3923, "lon": 2.1610, "cat": "gastronomy", "tags": ["michelin", "luxury"] },
    { "name": "ABaC", "lat": 41.4105, "lon": 2.1378, "cat": "gastronomy", "tags": ["michelin", "hotel"] },
    { "name": "Enigma", "lat": 41.3745, "lon": 2.1652, "cat": "gastronomy", "tags": ["innovative", "adría"] },
    { "name": "Moments", "lat": 41.3925, "lon": 2.1612, "cat": "gastronomy", "tags": ["michelin", "hotel"] },
    { "name": "Cocina Hermanos Torres", "lat": 41.3872, "lon": 2.1331, "cat": "gastronomy", "tags": ["michelin", "kitchen"] },
    { "name": "Gresca", "lat": 41.3920, "lon": 2.1585, "cat": "gastronomy", "tags": ["bistrot", "wine"] },
    { "name": "Bar Mut", "lat": 41.3955, "lon": 2.1622, "cat": "gastronomy", "tags": ["wine", "tapas"] },
    { "name": "Tapas 24", "lat": 41.3912, "lon": 2.1685, "cat": "gastronomy", "tags": ["tapas", "modern"] },
    { "name": "Bodega 1900", "lat": 41.3755, "lon": 2.1560, "cat": "gastronomy", "tags": ["vermouth", "bodega"] },
    { "name": "Pinotxo Bar", "lat": 41.3817, "lon": 2.1718, "cat": "gastronomy", "tags": ["market", "breakfast"] },
    { "name": "Can Roca (Girona Bar)", "lat": 41.9835, "lon": 2.8220, "cat": "gastronomy", "tags": ["traditional", "cheap"] },
    { "name": "Nu Restaurant", "lat": 41.9845, "lon": 2.8235, "cat": "gastronomy", "tags": ["asian", "fusion"] },
    { "name": "Les Cols", "lat": 42.1865, "lon": 2.4985, "cat": "gastronomy", "tags": ["michelin", "nature"] },
    { "name": "Miramar", "lat": 42.3685, "lon": 3.1605, "cat": "gastronomy", "tags": ["seafood", "michelin"] },
    { "name": "Els Tinars", "lat": 41.8215, "lon": 2.9465, "cat": "gastronomy", "tags": ["traditional", "michelin"] },
    { "name": "Ca l'Enric", "lat": 42.2355, "lon": 2.4465, "cat": "gastronomy", "tags": ["mountain", "michelin"] },
    { "name": "Boadas Cocktails", "lat": 41.3845, "lon": 2.1705, "cat": "gastronomy", "tags": ["cocktail", "historic"] },
    { "name": "Bar Central", "lat": 41.3820, "lon": 2.1720, "cat": "gastronomy", "tags": ["market", "fresh"] },
    { "name": "El Vaso de Oro", "lat": 41.3805, "lon": 2.1865, "cat": "gastronomy", "tags": ["beer", "tapas"] },
    { "name": "La Cova Fumada", "lat": 41.3780, "lon": 2.1895, "cat": "gastronomy", "tags": ["bomba", "tapas"] },
    { "name": "Jai-Ca", "lat": 41.3790, "lon": 2.1885, "cat": "gastronomy", "tags": ["vermouth", "tapas"] },
    { "name": "Mussol Casp", "lat": 41.3890, "lon": 2.1705, "cat": "gastronomy", "tags": ["catalan", "grill"] },
    { "name": "Ciudad Condal", "lat": 41.3895, "lon": 2.1665, "cat": "gastronomy", "tags": ["tapas", "busy"] },
    { "name": "Paco Meralgo", "lat": 41.3910, "lon": 2.1525, "cat": "gastronomy", "tags": ["tapas", "seafood"] },

    // --- NATURE (40) ---
    { "name": "Park Güell", "lat": 41.4145, "lon": 2.1527, "cat": "nature", "tags": ["gaudi", "park", "unesco"] },
    { "name": "Ciutadella Park", "lat": 41.3883, "lon": 2.1874, "cat": "nature", "tags": ["park", "lake"] },
    { "name": "Barceloneta Beach", "lat": 41.3784, "lon": 2.1925, "cat": "nature", "tags": ["beach", "sea"] },
    { "name": "Bogatell Beach", "lat": 41.3938, "lon": 2.2067, "cat": "nature", "tags": ["beach", "sea"] },
    { "name": "Cadaqués", "lat": 42.2887, "lon": 3.2779, "cat": "nature", "tags": ["beach", "white_village"] },
    { "name": "Cap de Creus", "lat": 42.3193, "lon": 3.3225, "cat": "nature", "tags": ["coast", "hiking"] },
    { "name": "Cala Pola", "lat": 41.7450, "lon": 2.9510, "cat": "nature", "tags": ["beach", "cove"] },
    { "name": "Jardins de Cap Roig", "lat": 41.8767, "lon": 3.1772, "cat": "nature", "tags": ["garden", "botanic"] },
    { "name": "Delta de l'Ebre", "lat": 40.7245, "lon": 0.8164, "cat": "nature", "tags": ["park", "birds"] },
    { "name": "Pedraforca", "lat": 42.2372, "lon": 1.7011, "cat": "nature", "tags": ["mountain", "hiking"] },
    { "name": "La Fageda d'en Jordà", "lat": 42.1488, "lon": 2.5135, "cat": "nature", "tags": ["forest", "volcano"] },
    { "name": "Aigüestortes National Park", "lat": 42.5690, "lon": 0.9423, "cat": "nature", "tags": ["park", "lakes"] },
    { "name": "Estany de Banyoles", "lat": 42.1197, "lon": 2.7578, "cat": "nature", "tags": ["lake", "rowing"] },
    { "name": "Vall de Núria", "lat": 42.3975, "lon": 2.1539, "cat": "nature", "tags": ["mountain", "ski"] },
    { "name": "Montseny Natural Park", "lat": 41.7785, "lon": 2.4005, "cat": "nature", "tags": ["forest", "unesco"] },
    { "name": "Garraf Natural Park", "lat": 41.2885, "lon": 1.9005, "cat": "nature", "tags": ["cliffs", "hike"] },
    { "name": "Cala Sa Tuna", "lat": 41.9615, "lon": 3.2265, "cat": "nature", "tags": ["beach", "picturesque"] },
    { "name": "Cala Aiguablava", "lat": 41.9360, "lon": 3.2185, "cat": "nature", "tags": ["beach", "blue_water"] },
    { "name": "Platja de Castell", "lat": 41.8625, "lon": 3.1555, "cat": "nature", "tags": ["beach", "wild"] },
    { "name": "Congost de Mont-rebei", "lat": 42.0965, "lon": 0.6965, "cat": "nature", "tags": ["canyon", "kayak"] },
    { "name": "Serra del Cadí", "lat": 42.2855, "lon": 1.6365, "cat": "nature", "tags": ["mountain", "park"] },
    { "name": "Estany de Sant Maurici", "lat": 42.5805, "lon": 1.0005, "cat": "nature", "tags": ["lake", "iconic"] },
    { "name": "Fonts del Llobregat", "lat": 42.2825, "lon": 2.0085, "cat": "nature", "tags": ["waterfall", "source"] },
    { "name": "Pantà de Sau", "lat": 41.9705, "lon": 2.3945, "cat": "nature", "tags": ["reservoir", "bell_tower"] },
    { "name": "Salt de Sallent", "lat": 42.0085, "lon": 2.4705, "cat": "nature", "tags": ["waterfall", "view"] },
    { "name": "Platja del Trabucador", "lat": 40.6125, "lon": 0.7265, "cat": "nature", "tags": ["beach", "kitesurf"] },
    { "name": "Far de Cap de Creus", "lat": 42.3210, "lon": 3.3230, "cat": "nature", "tags": ["lighthouse", "end_of_world"] },
    { "name": "Zona Volcànica de la Garrotxa", "lat": 42.1505, "lon": 2.5505, "cat": "nature", "tags": ["volcanoes", "green"] },
    { "name": "Saut deth Pish", "lat": 42.7755, "lon": 0.8265, "cat": "nature", "tags": ["waterfall", "aran"] },
    { "name": "Estany de Malniu", "lat": 42.4635, "lon": 1.7865, "cat": "nature", "tags": ["lake", "hike"] },
    { "name": "Cala Treumal", "lat": 41.6880, "lon": 2.8130, "cat": "nature", "tags": ["beach", "blanes"] },
    { "name": "Jardí Botànic Marimurtra", "lat": 41.6755, "lon": 2.8025, "cat": "nature", "tags": ["garden", "cliffs"] },
    { "name": "Cala Giverola", "lat": 41.7335, "lon": 2.9465, "cat": "nature", "tags": ["beach", "cove"] },
    { "name": "Platja de la Marquesa", "lat": 40.7580, "lon": 0.8120, "cat": "nature", "tags": ["beach", "dunes"] },
    { "name": "Gorgs de la Cabriola", "lat": 42.2150, "lon": 2.0550, "cat": "nature", "tags": ["waterfall", "hike"] },
    { "name": "Riera de Merlès", "lat": 41.9880, "lon": 1.9950, "cat": "nature", "tags": ["river", "swim"] },
    { "name": "Platja de Pals", "lat": 42.0005, "lon": 3.2055, "cat": "nature", "tags": ["beach", "long"] },
    { "name": "Illes Medes", "lat": 42.0390, "lon": 3.2230, "cat": "nature", "tags": ["islands", "diving"] },
    { "name": "Camí de Ronda", "lat": 41.9540, "lon": 3.2100, "cat": "nature", "tags": ["hiking", "coast"] },
    { "name": "La Mola", "lat": 41.6415, "lon": 2.0195, "cat": "nature", "tags": ["mountain", "monastery"] },

    // --- NIGHTLIFE (30) ---
    { "name": "Magic Fountain of Montjuïc", "lat": 41.3712, "lon": 2.1517, "cat": "nightlife", "tags": ["show", "lights"] },
    { "name": "Razzmatazz", "lat": 41.3977, "lon": 2.1911, "cat": "nightlife", "tags": ["club", "music"] },
    { "name": "Sala Apolo", "lat": 41.3744, "lon": 2.1695, "cat": "nightlife", "tags": ["club", "concerts"] },
    { "name": "Sutton Club", "lat": 41.3970, "lon": 2.1488, "cat": "nightlife", "tags": ["club", "posh"] },
    { "name": "Opium Barcelona", "lat": 41.3857, "lon": 2.1965, "cat": "nightlife", "tags": ["club", "beach"] },
    { "name": "Pacha Barcelona", "lat": 41.3855, "lon": 2.1969, "cat": "nightlife", "tags": ["club", "beach"] },
    { "name": "Paradiso", "lat": 41.3837, "lon": 2.1824, "cat": "nightlife", "tags": ["cocktails", "speakeasy"] },
    { "name": "Dr. Stravinsky", "lat": 41.3830, "lon": 2.1804, "cat": "nightlife", "tags": ["cocktails", "mixology"] },
    { "name": "Bar Marsella", "lat": 41.3787, "lon": 2.1718, "cat": "nightlife", "tags": ["absinthe", "historic"] },
    { "name": "W Hotel", "lat": 41.3685, "lon": 2.1908, "cat": "nightlife", "tags": ["hotel", "iconic"] },
    { "name": "Eclipse Bar", "lat": 41.3685, "lon": 2.1908, "cat": "nightlife", "tags": ["view", "cocktails"] },
    { "name": "La Mirona", "lat": 41.9667, "lon": 2.7833, "cat": "nightlife", "tags": ["concerts", "girona"] },
    { "name": "Moog", "lat": 41.3795, "lon": 2.1735, "cat": "nightlife", "tags": ["techno", "club"] },
    { "name": "Jamboree", "lat": 41.3798, "lon": 2.1745, "cat": "nightlife", "tags": ["jazz", "club"] },
    { "name": "Sidecar Factory Club", "lat": 41.3800, "lon": 2.1748, "cat": "nightlife", "tags": ["rock", "live"] },
    { "name": "Bling Bling", "lat": 41.3965, "lon": 2.1520, "cat": "nightlife", "tags": ["club", "posh"] },
    { "name": "Otto Zutz", "lat": 41.4005, "lon": 2.1505, "cat": "nightlife", "tags": ["club", "urban"] },
    { "name": "La Terrrazza", "lat": 41.3680, "lon": 2.1485, "cat": "nightlife", "tags": ["open_air", "house"] },
    { "name": "City Hall", "lat": 41.3865, "lon": 2.1695, "cat": "nightlife", "tags": ["club", "techno"] },
    { "name": "Macarena Club", "lat": 41.3805, "lon": 2.1755, "cat": "nightlife", "tags": ["microclub", "techno"] },
    { "name": "Heliogàbal", "lat": 41.4035, "lon": 2.1610, "cat": "nightlife", "tags": ["live", "gracia"] },
    { "name": "L'Ovella Negra", "lat": 41.3815, "lon": 2.1700, "cat": "nightlife", "tags": ["beer", "rustic"] },
    { "name": "London Bar", "lat": 41.3780, "lon": 2.1730, "cat": "nightlife", "tags": ["historic", "modernist"] },
    { "name": "Casino Barcelona", "lat": 41.3860, "lon": 2.1970, "cat": "nightlife", "tags": ["casino", "games"] },
    { "name": "Icebarcelona", "lat": 41.3850, "lon": 2.1960, "cat": "nightlife", "tags": ["ice", "drinks"] },
    { "name": "Luz de Gas", "lat": 41.3950, "lon": 2.1480, "cat": "nightlife", "tags": ["concerts", "club"] },
    { "name": "Bikini", "lat": 41.3880, "lon": 2.1330, "cat": "nightlife", "tags": ["concerts", "club"] },
    { "name": "Vol", "lat": 41.3990, "lon": 2.1900, "cat": "nightlife", "tags": ["rock", "bar"] },
    { "name": "Nevermind", "lat": 41.3830, "lon": 2.1660, "cat": "nightlife", "tags": ["skate", "bar"] },
    { "name": "Sor Rita", "lat": 41.3800, "lon": 2.1790, "cat": "nightlife", "tags": ["kitsch", "cocktails"] },

    // --- SHOPPING (30) ---
    { "name": "Sant Antoni Market", "lat": 41.3788, "lon": 2.1630, "cat": "shopping", "tags": ["market", "renovated"] },
    { "name": "Passeig de Gràcia", "lat": 41.3926, "lon": 2.1654, "cat": "shopping", "tags": ["luxury", "brands"] },
    { "name": "Portal de l'Àngel", "lat": 41.3865, "lon": 2.1729, "cat": "shopping", "tags": ["highstreet", "busy"] },
    { "name": "La Roca Village", "lat": 41.6112, "lon": 2.3436, "cat": "shopping", "tags": ["outlet", "brands"] },
    { "name": "L'Illa Diagonal", "lat": 41.3892, "lon": 2.1356, "cat": "shopping", "tags": ["mall", "modern"] },
    { "name": "Encants Vells", "lat": 41.4010, "lon": 2.1862, "cat": "shopping", "tags": ["flea_market", "antiques"] },
    { "name": "La Maquinista", "lat": 41.4402, "lon": 2.1994, "cat": "shopping", "tags": ["mall", "open_air"] },
    { "name": "Diagonal Mar", "lat": 41.4111, "lon": 2.2155, "cat": "shopping", "tags": ["mall", "sea"] },
    { "name": "Mercat del Lleó", "lat": 41.9818, "lon": 2.8228, "cat": "shopping", "tags": ["market", "girona"] },
    { "name": "Espai Gironès", "lat": 41.9564, "lon": 2.7937, "cat": "shopping", "tags": ["mall", "salt"] },
    { "name": "Mercat Central de Tarragona", "lat": 41.1158, "lon": 1.2520, "cat": "shopping", "tags": ["market", "historic"] },
    { "name": "Carrer de Petritxol", "lat": 41.3828, "lon": 2.1732, "cat": "shopping", "tags": ["chocolate", "art"] },
    { "name": "El Born Centre Cultural", "lat": 41.3855, "lon": 2.1835, "cat": "shopping", "tags": ["history", "shops"] },
    { "name": "Gràcia Neighborhood", "lat": 41.4025, "lon": 2.1560, "cat": "shopping", "tags": ["boutiques", "local"] },
    { "name": "Carrer d'Avinyó", "lat": 41.3810, "lon": 2.1770, "cat": "shopping", "tags": ["fashion", "trendy"] },
    { "name": "Carrer de la Portaferrissa", "lat": 41.3840, "lon": 2.1735, "cat": "shopping", "tags": ["pedestrian", "shops"] },
    { "name": "Arenas de Barcelona", "lat": 41.3755, "lon": 2.1490, "cat": "shopping", "tags": ["mall", "bullring"] },
    { "name": "Glòries Shopping Centre", "lat": 41.4060, "lon": 2.1930, "cat": "shopping", "tags": ["mall", "modern"] },
    { "name": "Viladecans The Style Outlets", "lat": 41.3060, "lon": 2.0220, "cat": "shopping", "tags": ["outlet", "clothes"] },
    { "name": "Mataró Parc", "lat": 41.5540, "lon": 2.4280, "cat": "shopping", "tags": ["mall", "mataro"] },
    { "name": "Gran Jonquera Outlet", "lat": 42.4040, "lon": 2.8800, "cat": "shopping", "tags": ["outlet", "border"] },
    { "name": "Mercat de Santa Caterina", "lat": 41.3860, "lon": 2.1780, "cat": "shopping", "tags": ["market", "roof"] },
    { "name": "El Triangle", "lat": 41.3855, "lon": 2.1700, "cat": "shopping", "tags": ["mall", "central"] },
    { "name": "Maremagnum", "lat": 41.3750, "lon": 2.1820, "cat": "shopping", "tags": ["mall", "harbour"] },
    { "name": "Rambla de Catalunya", "lat": 41.3900, "lon": 2.1630, "cat": "shopping", "tags": ["boulevard", "shops"] },
    { "name": "Carrer de Sants", "lat": 41.3750, "lon": 2.1350, "cat": "shopping", "tags": ["local", "busy"] },
    { "name": "L'Eix Comercial Raval", "lat": 41.3800, "lon": 2.1680, "cat": "shopping", "tags": ["vintage", "unique"] },
    { "name": "Mercantic", "lat": 41.4720, "lon": 2.0670, "cat": "shopping", "tags": ["antiques", "market"] },
    { "name": "Palo Alto Market", "lat": 41.4050, "lon": 2.2100, "cat": "shopping", "tags": ["design", "weekend"] },
    { "name": "Lost & Found Market", "lat": 41.3780, "lon": 2.1890, "cat": "shopping", "tags": ["vintage", "secondhand"] },

    // --- WELLNESS (20) ---
    { "name": "Aire Ancient Baths", "lat": 41.3867, "lon": 2.1824, "cat": "wellness", "tags": ["spa", "relax"] },
    { "name": "Carretera de les Aigües", "lat": 41.4172, "lon": 2.1150, "cat": "wellness", "tags": ["running", "cycling", "views"] },
    { "name": "Club Natació Atlètic-Barceloneta", "lat": 41.3742, "lon": 2.1890, "cat": "wellness", "tags": ["pool", "gym", "sea"] },
    { "name": "Banys Àrabs", "lat": 41.9872, "lon": 2.8258, "cat": "wellness", "tags": ["history", "girona"] },
    { "name": "Balneari Vichy Catalan", "lat": 41.8369, "lon": 2.8058, "cat": "wellness", "tags": ["spa", "thermal", "hotel"] },
    { "name": "Magma Centre Lúdic", "lat": 41.8596, "lon": 2.6625, "cat": "wellness", "tags": ["spa", "thermal"] },
    { "name": "Parc de la Creueta del Coll", "lat": 41.4184, "lon": 2.1466, "cat": "wellness", "tags": ["pool", "relax"] },
    { "name": "W Barcelona Spa", "lat": 41.3685, "lon": 2.1908, "cat": "wellness", "tags": ["spa", "luxury"] },
    { "name": "Hotel Arts 43 The Spa", "lat": 41.3865, "lon": 2.1965, "cat": "wellness", "tags": ["spa", "views"] },
    { "name": "Mayan Secret Spa", "lat": 41.3905, "lon": 2.1710, "cat": "wellness", "tags": ["spa", "mayan"] },
    { "name": "Rituels d'Orient", "lat": 41.3955, "lon": 2.1490, "cat": "wellness", "tags": ["hammam", "massage"] },
    { "name": "Slow Spa", "lat": 41.3920, "lon": 2.1550, "cat": "wellness", "tags": ["organic", "relax"] },
    { "name": "Flax & Kale", "lat": 41.3855, "lon": 2.1660, "cat": "wellness", "tags": ["healthy_food", "flexitarian"] },
    { "name": "YogaOne", "lat": 41.3930, "lon": 2.1640, "cat": "wellness", "tags": ["yoga", "classes"] },
    { "name": "Piscines Bernat Picornell", "lat": 41.3655, "lon": 2.1530, "cat": "wellness", "tags": ["pool", "olympic"] },
    { "name": "Banys de Sant Vicenç", "lat": 42.3680, "lon": 1.6030, "cat": "wellness", "tags": ["thermal", "pyrenees"] },
    { "name": "Balneari Broquetas", "lat": 41.6335, "lon": 2.1665, "cat": "wellness", "tags": ["thermal", "historic"] },
    { "name": "Silence Spa", "lat": 41.5200, "lon": 2.4350, "cat": "wellness", "tags": ["caldea", "thermal"] },
    { "name": "Vallromanes Golf and Spa", "lat": 41.5300, "lon": 2.2950, "cat": "wellness", "tags": ["golf", "spa"] },
    { "name": "Mas de Torrent", "lat": 41.9540, "lon": 3.1250, "cat": "wellness", "tags": ["luxury", "retreat"] },

    // --- EDUCATION (20) ---
    { "name": "University of Barcelona (Historic)", "lat": 41.3868, "lon": 2.1642, "cat": "education", "tags": ["university", "history"] },
    { "name": "Biblioteca de Catalunya", "lat": 41.3813, "lon": 2.1706, "cat": "education", "tags": ["library", "books"] },
    { "name": "CosmoCaixa", "lat": 41.4132, "lon": 2.1317, "cat": "education", "tags": ["science", "museum"] },
    { "name": "Museu Blau", "lat": 41.4116, "lon": 2.2205, "cat": "education", "tags": ["science", "museum"] },
    { "name": "Museu de la Ciència (Terrassa)", "lat": 41.5694, "lon": 2.0125, "cat": "education", "tags": ["industry", "museum"] },
    { "name": "Museu d'Història de Catalunya", "lat": 41.3808, "lon": 2.1865, "cat": "education", "tags": ["history", "museum"] },
    { "name": "Museu d'Arqueologia de Catalunya", "lat": 41.3705, "lon": 2.1575, "cat": "education", "tags": ["archaeology", "history"] },
    { "name": "Museu del Disseny", "lat": 41.4025, "lon": 2.1885, "cat": "education", "tags": ["design", "museum"] },
    { "name": "CCCB", "lat": 41.3830, "lon": 2.1665, "cat": "education", "tags": ["culture", "contemporary"] },
    { "name": "MACBA", "lat": 41.3832, "lon": 2.1669, "cat": "education", "tags": ["art", "museum"] },
    { "name": "Fundació Tàpies", "lat": 41.3915, "lon": 2.1635, "cat": "education", "tags": ["art", "library"] },
    { "name": "Museu de la Xocolata", "lat": 41.3875, "lon": 2.1815, "cat": "education", "tags": ["chocolate", "workshop"] },
    { "name": "Museu Egipci", "lat": 41.3915, "lon": 2.1665, "cat": "education", "tags": ["egypt", "history"] },
    { "name": "Biblioteca Gabriel García Márquez", "lat": 41.4180, "lon": 2.1985, "cat": "education", "tags": ["library", "modern"] },
    { "name": "UAB Campus", "lat": 41.5030, "lon": 2.1080, "cat": "education", "tags": ["university", "campus"] },
    { "name": "Pompeu Fabra Campus", "lat": 41.3880, "lon": 2.1860, "cat": "education", "tags": ["university", "campus"] },
    { "name": "Museu Episcopal de Vic", "lat": 41.9295, "lon": 2.2560, "cat": "education", "tags": ["art", "medieval"] },
    { "name": "Museu del Cinema (Girona)", "lat": 41.9830, "lon": 2.8235, "cat": "education", "tags": ["film", "history"] },
    { "name": "Museu del Joguet (Figueres)", "lat": 42.2665, "lon": 2.9610, "cat": "education", "tags": ["toys", "museum"] },
    { "name": "Ecomuseu de les Valls d'Àneu", "lat": 42.6280, "lon": 1.1090, "cat": "education", "tags": ["ethnography", "pyrenees"] },

    // --- HIDDEN GEMS (20) ---
    { "name": "Bunker del Carmel", "lat": 41.4193, "lon": 2.1616, "cat": "hidden_gems", "tags": ["view", "history"] },
    { "name": "Jardins de la Tamarita", "lat": 41.4114, "lon": 2.1360, "cat": "hidden_gems", "tags": ["garden", "quiet"] },
    { "name": "Parc del Laberint d'Horta", "lat": 41.4391, "lon": 2.1458, "cat": "hidden_gems", "tags": ["garden", "maze"] },
    { "name": "Cala S'Alguer", "lat": 41.8606, "lon": 3.1554, "cat": "hidden_gems", "tags": ["fishing_village", "cove"] },
    { "name": "Castell de Burriac", "lat": 41.5372, "lon": 2.3853, "cat": "hidden_gems", "tags": ["ruins", "hike"] },
    { "name": "Monestir de Sant Pere de Rodes", "lat": 42.3235, "lon": 3.1654, "cat": "hidden_gems", "tags": ["monastery", "view"] },
    { "name": "Cactus Garden (Montjuïc)", "lat": 41.3653, "lon": 2.1678, "cat": "hidden_gems", "tags": ["plants", "view"] },
    { "name": "Refugi 307", "lat": 41.3705, "lon": 2.1675, "cat": "hidden_gems", "tags": ["shelter", "history"] },
    { "name": "Plaça de Sant Felip Neri", "lat": 41.3830, "lon": 2.1750, "cat": "hidden_gems", "tags": ["square", "quiet"] },
    { "name": "Jardins de Laribal", "lat": 41.3685, "lon": 2.1585, "cat": "hidden_gems", "tags": ["garden", "fountain"] },
    { "name": "Claustre de la Catedral", "lat": 41.3840, "lon": 2.1760, "cat": "hidden_gems", "tags": ["geese", "peaceful"] },
    { "name": "Carrer del Bisbe", "lat": 41.3835, "lon": 2.1765, "cat": "hidden_gems", "tags": ["bridge", "gothic"] },
    { "name": "Palau Baró de Quadras", "lat": 41.3960, "lon": 2.1610, "cat": "hidden_gems", "tags": ["modernisme", "museum"] },
    { "name": "Casa Vicens", "lat": 41.4035, "lon": 2.1505, "cat": "hidden_gems", "tags": ["gaudi", "first"] },
    { "name": "Torre Bellesguard", "lat": 41.4095, "lon": 2.1270, "cat": "hidden_gems", "tags": ["gaudi", "castle"] },
    { "name": "Plaça del Diamant", "lat": 41.4025, "lon": 2.1565, "cat": "hidden_gems", "tags": ["gracia", "history"] },
    { "name": "Jardins de Pedralbes", "lat": 41.3880, "lon": 2.1170, "cat": "hidden_gems", "tags": ["garden", "palace"] },
    { "name": "Parc de Cervantes", "lat": 41.3840, "lon": 2.1050, "cat": "hidden_gems", "tags": ["roses", "park"] },
    { "name": "Mirador de l'Alcalde", "lat": 41.3680, "lon": 2.1680, "cat": "hidden_gems", "tags": ["view", "sea"] },
    { "name": "Pont del Petroli", "lat": 41.4330, "lon": 2.2470, "cat": "hidden_gems", "tags": ["bridge", "sea"] },

    // --- FAMILY (30) ---
    { "name": "Tibidabo Amusement Park", "lat": 41.4223, "lon": 2.1194, "cat": "family", "tags": ["fun", "view", "vintage"] },
    { "name": "Barcelona Zoo", "lat": 41.3860, "lon": 2.1895, "cat": "family", "tags": ["animals", "park"] },
    { "name": "L'Aquàrium", "lat": 41.3770, "lon": 2.1843, "cat": "family", "tags": ["fish", "sea"] },
    { "name": "PortAventura World", "lat": 41.0878, "lon": 1.1574, "cat": "family", "tags": ["theme_park", "rollercoasters"] },
    { "name": "Catalunya en Miniatura", "lat": 41.3608, "lon": 1.9961, "cat": "family", "tags": ["miniature", "park"] },
    { "name": "Parc de l'Oreneta", "lat": 41.4017, "lon": 2.1122, "cat": "family", "tags": ["train", "forest"] },
    { "name": "Marineland Catalunya", "lat": 41.6732, "lon": 2.7303, "cat": "family", "tags": ["waterpark", "dolphins"] },
    { "name": "Bosc Urbà", "lat": 41.4110, "lon": 2.2200, "cat": "family", "tags": ["adventure", "climbing"] },
    { "name": "Granja d'Aventura Park", "lat": 41.5940, "lon": 2.3780, "cat": "family", "tags": ["farm", "animals"] },
    { "name": "Jumpland Aventura", "lat": 41.0800, "lon": 1.0400, "cat": "family", "tags": ["zipline", "adventure"] },
    { "name": "Ferrari Land", "lat": 41.0860, "lon": 1.1550, "cat": "family", "tags": ["ferrari", "speed"] },
    { "name": "Caribe Aquatic Park", "lat": 41.0880, "lon": 1.1520, "cat": "family", "tags": ["waterpark", "portaventura"] },
    { "name": "Water World", "lat": 41.7060, "lon": 2.8250, "cat": "family", "tags": ["waterpark", "slides"] },
    { "name": "Illa Fantasia", "lat": 41.5050, "lon": 2.3580, "cat": "family", "tags": ["waterpark", "family"] },
    { "name": "Parc Samà", "lat": 41.1040, "lon": 1.0260, "cat": "family", "tags": ["botanic", "animals"] },
    { "name": "Butterfly Park", "lat": 42.2530, "lon": 3.1000, "cat": "family", "tags": ["butterflies", "tropical"] },
    { "name": "Aquabrava", "lat": 42.2700, "lon": 3.1400, "cat": "family", "tags": ["waterpark", "roses"] },
    { "name": "Gnomo Park", "lat": 41.6900, "lon": 2.8200, "cat": "family", "tags": ["kids", "fun"] },
    { "name": "Pp's Park", "lat": 41.8150, "lon": 3.0650, "cat": "family", "tags": ["rides", "platjadaro"] },
    { "name": "Aqualeon", "lat": 41.2500, "lon": 1.4800, "cat": "family", "tags": ["safari", "waterpark"] },
    { "name": "Món Sant Benet", "lat": 41.7420, "lon": 1.8990, "cat": "family", "tags": ["monastery", "workshops"] },
    { "name": "Rukimon", "lat": 41.6150, "lon": 2.5000, "cat": "family", "tags": ["donkeys", "nature"] },
    { "name": "Fundació CRAM", "lat": 41.2900, "lon": 2.1000, "cat": "family", "tags": ["turtles", "rescue"] },
    { "name": "Museu del Ferrocarril", "lat": 41.2200, "lon": 1.7300, "cat": "family", "tags": ["trains", "history"] },
    { "name": "Vall de Núria (Family)", "lat": 42.4000, "lon": 2.1500, "cat": "family", "tags": ["snow", "train"] },
    { "name": "Parc de la Pegaso", "lat": 41.4300, "lon": 2.1900, "cat": "family", "tags": ["octopus", "park"] },
    { "name": "Parc Central de Nou Barris", "lat": 41.4400, "lon": 2.1700, "cat": "family", "tags": ["park", "fountain"] },
    { "name": "Tobogan de Calafell", "lat": 41.1900, "lon": 1.5700, "cat": "family", "tags": ["slide", "fun"] },
    { "name": "Karting Cardedeu", "lat": 41.6400, "lon": 2.3600, "cat": "family", "tags": ["karting", "racing"] },
    { "name": "Indoor Jumping Club", "lat": 41.4200, "lon": 2.2000, "cat": "family", "tags": ["trampoline", "jump"] },

    { name: "Cala Sa Boadella", lat: 41.693, lon: 2.818, cat: 'nature', tags: ["beach", "cove"] },
    { name: "Platja de Fenals", lat: 41.695, lon: 2.833, cat: 'nature', tags: ["beach", "popular"] },
    { name: "Cala Canyelles", lat: 41.705, lon: 2.88, cat: 'nature', tags: ["beach", "port"] },
    { name: "Cala Futadera", lat: 41.74, lon: 2.956, cat: 'nature', tags: ["beach", "cove"] },
    { name: "Cala Bona", lat: 41.738, lon: 2.95, cat: 'nature', tags: ["beach", "snorkeling"] },
    { name: "Platja Gran de Tossa", lat: 41.718, lon: 2.934, cat: 'nature', tags: ["beach", "castle_view"] },
    { name: "Platja del Canadell", lat: 41.888, lon: 3.183, cat: 'nature', tags: ["beach", "promenade"] },
    { name: "Platja de Llafranc", lat: 41.893, lon: 3.195, cat: 'nature', tags: ["beach", "family"] },
    { name: "Platja de Tamariu", lat: 41.918, lon: 3.208, cat: 'nature', tags: ["beach", "diving"] },
    { name: "Cala d'Aigua Xelida", lat: 41.923, lon: 3.213, cat: 'nature', tags: ["beach", "secluded"] },
    { name: "Platja del Racó", lat: 41.983, lon: 3.206, cat: 'nature', tags: ["beach", "begur"] },
    { name: "Illa Roja", lat: 41.98, lon: 3.205, cat: 'nature', tags: ["beach", "nudist"] },
    { name: "Sa Riera", lat: 41.973, lon: 3.208, cat: 'nature', tags: ["beach", "fishing_village"] },
    { name: "Cala Montgó", lat: 42.11, lon: 3.168, cat: 'nature', tags: ["beach", "cliffs"] },
    { name: "Platja de Riells", lat: 42.118, lon: 3.143, cat: 'nature', tags: ["beach", "shallow"] },
    { name: "Platja de Sant Pere Pescador", lat: 42.195, lon: 3.103, cat: 'nature', tags: ["beach", "windsurf"] },
    { name: "Platja de la Rubina", lat: 42.245, lon: 3.145, cat: 'nature', tags: ["beach", "dog_friendly"] },
    { name: "Cala Joncols", lat: 42.26, lon: 3.243, cat: 'nature', tags: ["beach", "remote"] },
    { name: "Cala Montjoi", lat: 42.25, lon: 3.226, cat: 'nature', tags: ["beach", "elbulli"] },
    { name: "Platja de Ribes Roges", lat: 41.213, lon: 1.723, cat: 'nature', tags: ["beach", "vilanova"] },
    { name: "Platja de Cunit", lat: 41.192, lon: 1.633, cat: 'nature', tags: ["beach", "family"] },
    { name: "Platja de Coma-ruga", lat: 41.183, lon: 1.533, cat: 'nature', tags: ["beach", "thermal"] },
    { name: "Platja de Sant Salvador", lat: 41.185, lon: 1.545, cat: 'nature', tags: ["beach", "museum"] },
    { name: "Platja de la Paella", lat: 41.143, lon: 1.403, cat: 'nature', tags: ["beach", "port"] },
    { name: "Platja d'Altafulla", lat: 41.135, lon: 1.378, cat: 'nature', tags: ["beach", "village"] },
    { name: "Platja Llarga (Tarragona)", lat: 41.128, lon: 1.298, cat: 'nature', tags: ["beach", "forest"] },
    { name: "Cala Fonda (Waikiki)", lat: 41.128, lon: 1.315, cat: 'nature', tags: ["beach", "wild"] },
    { name: "Platja del Miracle", lat: 41.113, lon: 1.258, cat: 'nature', tags: ["beach", "urban"] },
    { name: "Platja de la Pineda", lat: 41.095, lon: 1.178, cat: 'nature', tags: ["beach", "family"] },
    { name: "Cala Crancs", lat: 41.058, lon: 1.163, cat: 'nature', tags: ["beach", "cove"] },
    { name: "Platja de Llevant", lat: 41.075, lon: 1.143, cat: 'nature', tags: ["beach", "busy"] },
    { name: "Platja del Regueral", lat: 41.065, lon: 1.063, cat: 'nature', tags: ["beach", "cambrils"] },
    { name: "Platja de l'Alguer", lat: 40.883, lon: 0.803, cat: 'nature', tags: ["beach", "fishing"] },
    { name: "Cala Forn", lat: 40.898, lon: 0.813, cat: 'nature', tags: ["beach", "crystal_clear"] },
    { name: "Pals Old Town", lat: 41.971, lon: 3.146, cat: 'culture', tags: ["medieval", "cobblestone"] },
    { name: "Peratallada", lat: 41.977, lon: 3.091, cat: 'culture', tags: ["medieval", "stone"] },
    { name: "Monells", lat: 41.99, lon: 2.996, cat: 'culture', tags: ["medieval", "square"] },
    { name: "Madremanya", lat: 41.993, lon: 2.958, cat: 'culture', tags: ["village", "stone"] },
    { name: "Corçà", lat: 41.986, lon: 3.018, cat: 'culture', tags: ["village", "rural"] },
    { name: "Vulpellac", lat: 41.961, lon: 3.055, cat: 'culture', tags: ["castle", "village"] },
    { name: "Ullastret", lat: 42.0, lon: 3.068, cat: 'culture', tags: ["iberian", "ruins"] },
    { name: "Palau-sator", lat: 41.988, lon: 3.109, cat: 'culture', tags: ["tower", "village"] },
    { name: "Rupit", lat: 42.025, lon: 2.466, cat: 'culture', tags: ["suspension_bridge", "stone"] },
    { name: "Pruit", lat: 42.036, lon: 2.455, cat: 'culture', tags: ["rural", "church"] },
    { name: "Tavertet", lat: 41.996, lon: 2.418, cat: 'culture', tags: ["cliffs", "view"] },
    { name: "Cantonigròs", lat: 42.041, lon: 2.406, cat: 'culture', tags: ["nature", "waterfall"] },
    { name: "Santa Pau", lat: 42.146, lon: 2.571, cat: 'culture', tags: ["medieval", "volcanoes"] },
    { name: "Castellfollit de la Roca", lat: 42.219, lon: 2.549, cat: 'culture', tags: ["cliffs", "basalt"] },
    { name: "Beget", lat: 42.318, lon: 2.483, cat: 'culture', tags: ["remote", "romanesque"] },
    { name: "Camprodon", lat: 42.313, lon: 2.366, cat: 'culture', tags: ["bridge", "mountain"] },
    { name: "Setcases", lat: 42.375, lon: 2.301, cat: 'culture', tags: ["stone", "ski"] },
    { name: "Molló", lat: 42.348, lon: 2.406, cat: 'culture', tags: ["border", "church"] },
    { name: "Queralbs", lat: 42.349, lon: 2.163, cat: 'culture', tags: ["stone", "railway"] },
    { name: "Ribes de Freser", lat: 42.305, lon: 2.168, cat: 'culture', tags: ["valley", "rivers"] },
    { name: "Gósol", lat: 42.236, lon: 1.66, cat: 'culture', tags: ["picasso", "mountain"] },
    { name: "Bagà", lat: 42.251, lon: 1.861, cat: 'culture', tags: ["medieval", "square"] },
    { name: "Castellar de n'Hug", lat: 42.281, lon: 2.015, cat: 'culture', tags: ["lobregat", "stone"] },
    { name: "Sant Jaume de Frontanyà", lat: 42.188, lon: 2.023, cat: 'culture', tags: ["tiny", "church"] },
    { name: "Montblanc Walls", lat: 41.376, lon: 1.162, cat: 'culture', tags: ["walls", "medieval"] },
    { name: "Siurana", lat: 41.259, lon: 0.931, cat: 'culture', tags: ["cliffs", "view"] },
    { name: "Prades", lat: 41.309, lon: 0.988, cat: 'culture', tags: ["red_town", "square"] },
    { name: "Capafonts", lat: 41.295, lon: 1.026, cat: 'culture', tags: ["mountains", "rural"] },
    { name: "Horta de Sant Joan", lat: 40.956, lon: 0.316, cat: 'culture', tags: ["picasso", "els_ports"] },
    { name: "Miravet Castle", lat: 41.043, lon: 0.598, cat: 'culture', tags: ["river", "templar"] },
    { name: "Arnes", lat: 40.91, lon: 0.261, cat: 'culture', tags: ["stone", "rural"] },
    { name: "Batea", lat: 41.093, lon: 0.31, cat: 'culture', tags: ["wine", "medieval"] },
    { name: "Guimerà", lat: 41.565, lon: 1.185, cat: 'culture', tags: ["hilltop", "medieval"] },
    { name: "Vallbona de les Monges", lat: 41.525, lon: 1.088, cat: 'culture', tags: ["monastery", "cistercian"] },
    { name: "Verdú", lat: 41.61, lon: 1.143, cat: 'culture', tags: ["ceramics", "castle"] },
    { name: "Penelles Murals", lat: 41.716, lon: 0.966, cat: 'culture', tags: ["art", "graffiti"] },
    { name: "Àger", lat: 42.0, lon: 0.763, cat: 'culture', tags: ["stars", "paragliding"] },
    { name: "Igualada Leather Museum", lat: 41.578, lon: 1.616, cat: 'culture', tags: ["industry", "museum"] },
    { name: "Vilafranca Vinseum", lat: 41.346, lon: 1.698, cat: 'culture', tags: ["wine", "museum"] },
    { name: "Sant Sadurní Cava Centre", lat: 41.423, lon: 1.786, cat: 'culture', tags: ["cava", "experience"] },
    { name: "Valls Castells", lat: 41.285, lon: 1.25, cat: 'culture', tags: ["tradition", "towers"] },
    { name: "Amposta Bridge", lat: 40.713, lon: 0.578, cat: 'culture', tags: ["ebre", "bridge"] },
    { name: "Castell de la Suda (Tortosa)", lat: 40.814, lon: 0.523, cat: 'culture', tags: ["castle", "parador"] },
    { name: "Tortosa Cathedral", lat: 40.812, lon: 0.522, cat: 'culture', tags: ["gothic", "river"] },
    { name: "Gandesa Cooperative", lat: 41.053, lon: 0.438, cat: 'culture', tags: ["modernisme", "wine"] },
    { name: "Mora d'Ebre Castle", lat: 41.091, lon: 0.64, cat: 'culture', tags: ["river", "castle"] },
    { name: "Falset Castle", lat: 41.146, lon: 0.82, cat: 'culture', tags: ["wine", "history"] },
    { name: "Bodegas Torres", lat: 41.361, lon: 1.663, cat: 'gastronomy', tags: ["wine", "tour"] },
    { name: "Cavas Codorníu", lat: 41.428, lon: 1.796, cat: 'gastronomy', tags: ["cava", "architecture"] },
    { name: "Cavas Freixenet", lat: 41.422, lon: 1.791, cat: 'gastronomy', tags: ["cava", "historic"] },
    { name: "Recaredo", lat: 41.423, lon: 1.785, cat: 'gastronomy', tags: ["cava", "biodynamic"] },
    { name: "Gramona", lat: 41.424, lon: 1.788, cat: 'gastronomy', tags: ["cava", "premium"] },
    { name: "Jean Leon", lat: 41.398, lon: 1.693, cat: 'gastronomy', tags: ["wine", "pioneer"] },
    { name: "Parés Baltà", lat: 41.366, lon: 1.666, cat: 'gastronomy', tags: ["wine", "organic"] },
    { name: "Scala Dei Cartoixa", lat: 41.256, lon: 0.81, cat: 'gastronomy', tags: ["wine", "priorat"] },
    { name: "Mas Doix", lat: 41.233, lon: 0.85, cat: 'gastronomy', tags: ["wine", "exclusive"] },
    { name: "Clos Mogador", lat: 41.211, lon: 0.776, cat: 'gastronomy', tags: ["wine", "legend"] },
    { name: "Alvaro Palacios", lat: 41.213, lon: 0.778, cat: 'gastronomy', tags: ["wine", "famous"] },
    { name: "Castell de Peralada Winery", lat: 42.306, lon: 3.011, cat: 'gastronomy', tags: ["wine", "castle"] },
    { name: "Celler Espelt", lat: 42.326, lon: 3.1, cat: 'gastronomy', tags: ["wine", "modern"] },
    { name: "La Vinyeta", lat: 42.361, lon: 2.966, cat: 'gastronomy', tags: ["wine", "experience"] },
    { name: "Turó de l'Home", lat: 41.773, lon: 2.438, cat: 'nature', tags: ["peak", "view"] },
    { name: "Matagalls", lat: 41.805, lon: 2.381, cat: 'nature', tags: ["peak", "hike"] },
    { name: "Pantà de Santa Fe", lat: 41.776, lon: 2.463, cat: 'nature', tags: ["lake", "forest"] },
    { name: "Santuari de Puiggracios", lat: 41.708, lon: 2.246, cat: 'nature', tags: ["view", "sanctuary"] },
    { name: "Cingles de Bertí", lat: 41.716, lon: 2.233, cat: 'nature', tags: ["cliffs", "hike"] },
    { name: "Sant Miquel del Fai", lat: 41.715, lon: 2.19, cat: 'nature', tags: ["monastery", "waterfall"] },
    { name: "Mola de Sant Llorenç", lat: 41.641, lon: 2.016, cat: 'nature', tags: ["mountain", "landmark"] },
    { name: "Montcau", lat: 41.661, lon: 1.993, cat: 'nature', tags: ["mountain", "rocky"] },
    { name: "Santuari de Queralt", lat: 42.106, lon: 1.83, cat: 'nature', tags: ["balcony", "berga"] },
    { name: "Rasos de Peguera", lat: 42.138, lon: 1.763, cat: 'nature', tags: ["snow", "nature"] },
    { name: "Port del Comte", lat: 42.173, lon: 1.563, cat: 'nature', tags: ["ski", "mountain"] },
    { name: "Pica d'Estats", lat: 42.671, lon: 1.396, cat: 'nature', tags: ["highest", "peak"] },
    { name: "Estany Llong", lat: 42.571, lon: 0.945, cat: 'nature', tags: ["lake", "hike"] },
    { name: "Aigüestortes Planell", lat: 42.553, lon: 0.946, cat: 'nature', tags: ["wetlands", "accessible"] },
    { name: "MónNatura Delta", lat: 40.661, lon: 0.776, cat: 'nature', tags: ["salt", "birds"] },
    { name: "Punta del Fangar", lat: 40.783, lon: 0.776, cat: 'nature', tags: ["lighthouse", "dunes"] },
    { name: "Bosc de Virós", lat: 42.546, lon: 1.28, cat: 'nature', tags: ["forest", "iron"] },
    { name: "Museu d'Història dels Jueus", lat: 41.986, lon: 2.826, cat: 'education', tags: ["history", "girona"] },
    { name: "Casa Masó", lat: 41.985, lon: 2.824, cat: 'culture', tags: ["architecture", "girona"] },
    { name: "Museu Nacional Arqueològic Tarragona", lat: 41.117, lon: 1.258, cat: 'education', tags: ["roman", "museum"] },
    { name: "Pretori Romà", lat: 41.116, lon: 1.257, cat: 'culture', tags: ["tower", "view"] },
    { name: "Museu d'Art Modern Tarragona", lat: 41.116, lon: 1.256, cat: 'education', tags: ["art", "museum"] },
    { name: "Gaudí Centre Reus", lat: 41.155, lon: 1.108, cat: 'education', tags: ["gaudi", "interactive"] },
    { name: "Institut Pere Mata", lat: 41.168, lon: 1.096, cat: 'culture', tags: ["modernisme", "hospital"] },
    { name: "Casa Navàs", lat: 41.155, lon: 1.108, cat: 'culture', tags: ["modernisme", "jewel"] },
    { name: "Museu de Lleida", lat: 41.616, lon: 0.623, cat: 'education', tags: ["history", "art"] },
    { name: "Castell Templer de Gardeny", lat: 41.611, lon: 0.613, cat: 'culture', tags: ["templar", "castle"] },
    { name: "Museu de la Tècnica Manresa", lat: 41.731, lon: 1.831, cat: 'education', tags: ["technology", "water"] },
    { name: "La Seu Manresa", lat: 41.723, lon: 1.826, cat: 'culture', tags: ["gothic", "basilica"] },
    { name: "Cova de Sant Ignasi", lat: 41.722, lon: 1.831, cat: 'culture', tags: ["religious", "pilgrimage"] },
    { name: "mNACTEC", lat: 41.569, lon: 2.012, cat: 'education', tags: ["science", "industry"] },
    { name: "Masia Freixa", lat: 41.563, lon: 2.008, cat: 'culture', tags: ["modernisme", "arch"] },
    { name: "Seu d'Ègara", lat: 41.566, lon: 2.016, cat: 'culture', tags: ["visigoth", "unique"] },
    { name: "Torre de l'Aigua Sabadell", lat: 41.551, lon: 2.115, cat: 'culture', tags: ["tower", "modernisme"] },
    { name: "Mercat de la Llibertat", lat: 41.4, lon: 2.153, cat: 'shopping', tags: ["market", "gracia"] },
    { name: "Mercat de l'Abaceria", lat: 41.401, lon: 2.158, cat: 'shopping', tags: ["market", "traditional"] },
    { name: "Mercat de Galvany", lat: 41.396, lon: 2.143, cat: 'shopping', tags: ["market", "fancy"] },
    { name: "Mercat del Ninot", lat: 41.388, lon: 2.153, cat: 'shopping', tags: ["market", "foodie"] },
    { name: "Jardins de Mossèn Costa i Llobera", lat: 41.37, lon: 2.173, cat: 'nature', tags: ["cactus", "view"] },
    { name: "Telefèric del Port", lat: 41.373, lon: 2.188, cat: 'family', tags: ["cablecar", "view"] },
    { name: "Las Golondrinas", lat: 41.375, lon: 2.181, cat: 'family', tags: ["boat", "tour"] },
    { name: "Museu de Cera", lat: 41.377, lon: 2.176, cat: 'family', tags: ["wax", "museum"] },
    { name: "Basílica de la Mercè", lat: 41.379, lon: 2.179, cat: 'culture', tags: ["church", "patron"] },
    { name: "Plaça Reial", lat: 41.38, lon: 2.175, cat: 'culture', tags: ["square", "fountain"] },
    { name: "Plaça del Rei", lat: 41.384, lon: 2.177, cat: 'culture', tags: ["history", "medieval"] },
    { name: "Plaça Sant Jaume", lat: 41.382, lon: 2.177, cat: 'culture', tags: ["government", "square"] },
    { name: "Sinagoga Major", lat: 41.382, lon: 2.175, cat: 'culture', tags: ["jewish", "history"] },
    { name: "Temple d'August", lat: 41.383, lon: 2.177, cat: 'culture', tags: ["roman", "columns"] },
    { name: "Casa de l'Ardiaca", lat: 41.384, lon: 2.175, cat: 'culture', tags: ["history", "mailbox"] },
    { name: "Plaça de Catalunya", lat: 41.387, lon: 2.17, cat: 'culture', tags: ["center", "meeting"] },
    { name: "Font de Canaletes", lat: 41.385, lon: 2.17, cat: 'culture', tags: ["fountain", "barca"] },
    { name: "Teatre Liceu", lat: 41.38, lon: 2.173, cat: 'culture', tags: ["opera", "theatre"] },
    { name: "Teatre Poliorama", lat: 41.384, lon: 2.171, cat: 'culture', tags: ["theatre", "ramblas"] },
    { name: "Teatre Tívoli", lat: 41.389, lon: 2.171, cat: 'culture', tags: ["theatre", "historic"] },
    { name: "Palau Robert", lat: 41.396, lon: 2.161, cat: 'culture', tags: ["exhibitions", "garden"] },
    { name: "Casa Fuster", lat: 41.398, lon: 2.159, cat: 'culture', tags: ["modernisme", "hotel"] },
    { name: "Casa Comalat", lat: 41.397, lon: 2.161, cat: 'culture', tags: ["modernisme", "hidden"] },
    { name: "Casa les Punxes", lat: 41.399, lon: 2.166, cat: 'culture', tags: ["modernisme", "castle"] },
    { name: "Palau Macaya", lat: 41.401, lon: 2.17, cat: 'culture', tags: ["modernisme", "white"] },
    { name: "Casa Amatller", lat: 41.391, lon: 2.165, cat: 'culture', tags: ["modernisme", "chocolate"] },
    { name: "Casa Lleó Morera", lat: 41.391, lon: 2.166, cat: 'culture', tags: ["modernisme", "flowers"] },
    { name: "Antiga Fàbrica Estrella Damm", lat: 41.412, lon: 2.175, cat: 'culture', tags: ["beer", "events"] },
    { name: "La Seu d'Urgell Cathedral", lat: 42.358, lon: 1.461, cat: 'culture', tags: ["romanesque", "bishop"] },
    { name: "Parc del Segre", lat: 42.355, lon: 1.456, cat: 'family', tags: ["kayak", "olympic"] },
    { name: "Llívia Pharmacy", lat: 42.463, lon: 1.978, cat: 'culture', tags: ["oldest", "pharmacy"] },
    { name: "Puigcerdà Lake", lat: 42.435, lon: 1.926, cat: 'nature', tags: ["lake", "promenade"] },
    { name: "Bellver de Cerdanya", lat: 42.37, lon: 1.776, cat: 'culture', tags: ["walls", "history"] },
    { name: "Solsona Cathedral", lat: 41.993, lon: 1.518, cat: 'culture', tags: ["gothic", "virgin"] },
    { name: "Cardona Salt Mountain", lat: 41.903, lon: 1.673, cat: 'nature', tags: ["salt", "mine"] },
    { name: "Sant Llorenç de Morunys", lat: 42.136, lon: 1.591, cat: 'culture', tags: ["church", "altarpiece"] },
    { name: "Far de Calella", lat: 41.606, lon: 2.646, cat: 'culture', tags: ["lighthouse", "view"] },
    { name: "Castell de Santa Florentina", lat: 41.598, lon: 2.576, cat: 'culture', tags: ["castle", "got"] },
    { name: "Arenys de Mar Port", lat: 41.578, lon: 2.556, cat: 'gastronomy', tags: ["fish", "auction"] },
    { name: "Caldes d'Estrac Thermal", lat: 41.571, lon: 2.528, cat: 'wellness', tags: ["thermal", "baths"] },
    { name: "Badalona Museum", lat: 41.451, lon: 2.246, cat: 'education', tags: ["roman", "baetulo"] },
    { name: "Biblioteca Jaume Fuster", lat: 41.407, lon: 2.151, cat: 'education', tags: ["library", "modern"] },
    { name: "Biblioteca Sagrada Família", lat: 41.405, lon: 2.176, cat: 'education', tags: ["library", "gaudi_view"] },
    { name: "Centre Cívic Casa Golferichs", lat: 41.381, lon: 2.156, cat: 'culture', tags: ["modernisme", "events"] },
    { name: "Ateneu Barcelonès", lat: 41.384, lon: 2.171, cat: 'culture', tags: ["library", "garden"] },
    { name: "Filmoteca de Catalunya", lat: 41.378, lon: 2.17, cat: 'culture', tags: ["cinema", "archive"] },
    { name: "Sant Cugat Monastery", lat: 41.472, lon: 2.085, cat: 'culture', tags: ["cloister", "romanesque"] },
    { name: "Collserola Tower", lat: 41.417, lon: 2.113, cat: 'culture', tags: ["view", "telecom"] },
    { name: "Pantà de Vallvidrera", lat: 41.412, lon: 2.098, cat: 'nature', tags: ["lake", "walk"] },
    { name: "Santa Creu d'Olorda", lat: 41.416, lon: 2.056, cat: 'nature', tags: ["hermitage", "view"] },
    { name: "Castell de Pallejà", lat: 41.408, lon: 1.996, cat: 'culture', tags: ["castle", "library"] },
    { name: "Pont del Diable (Martorell)", lat: 41.476, lon: 1.936, cat: 'culture', tags: ["bridge", "roman"] },
    { name: "Montserrat Santa Cova", lat: 41.591, lon: 1.841, cat: 'culture', tags: ["chapel", "view"] },
    { name: "Montserrat Sant Jeroni", lat: 41.601, lon: 1.811, cat: 'nature', tags: ["peak", "hike"] },
    { name: "Coves del Salnitre", lat: 41.573, lon: 1.83, cat: 'nature', tags: ["caves", "collbato"] },
    { name: "Castell de Claramunt", lat: 41.611, lon: 1.698, cat: 'culture', tags: ["castle", "view"] },
    { name: "Molí Paperer de Capellades", lat: 41.53, lon: 1.685, cat: 'education', tags: ["paper", "museum"] },
    { name: "Castell de Gelida", lat: 41.438, lon: 1.866, cat: 'culture', tags: ["castle", "funicular"] },
    { name: "Castell de Subirats", lat: 41.413, lon: 1.813, cat: 'culture', tags: ["castle", "views"] },
  ];

  // 4. Save to Repo
  console.log("💾 Saving places using batching...");

  const entities = places.map(p => ({
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [p.lon, p.lat]
    },
    properties: {
      name: p.name,
      category: p.cat,
      tags: p.tags
    }
  }));

  await repo.saveAll(entities);

  console.log(`\n✅ Seeded ${entities.length} real places!`);
}

run();
